trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main
    always: true

stages:
  - stage: Test
    displayName: Test Terraform modules
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            persistCredentials: true
          - task: Docker@2
            displayName: Run Terraform modules tests
            inputs:
              command: build
              Dockerfile: '**/Dockerfile'
              addPipelineData: false
              addBaseImageData: false
              arguments: |
                --build-arg ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                --build-arg ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                --build-arg ARM_TENANT_ID=$(ARM_TENANT_ID)
                --build-arg ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
