trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'

schedules:
  - cron: "0 0 * * 6"
    displayName: Weekly midnight build
    branches:
      include:
        - main
    always: true

stages:
  - stage: Test
    displayName: Test Terraform modules
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              docker build \
                --build-arg ARM_CLIENT_ID=$(ARM_CLIENT_ID) \
                --build-arg ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET) \
                --build-arg ARM_TENANT_ID=$(ARM_TENANT_ID) \
                --build-arg ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID) \
                -t terraform_test \
                .
              docker run --network host -v /var/run/docker.sock:/var/run/docker.sock terraform_test
            displayName: Run Terraform modules tests
