FROM golang:golang:1.20.2

ARG ARM_CLIENT_ID
ARG ARM_CLIENT_SECRET
ARG ARM_TENANT_ID
ARG ARM_SUBSCRIPTION_ID

ENV ARM_CLIENT_ID $ARM_CLIENT_ID
ENV ARM_CLIENT_SECRET $ARM_CLIENT_SECRET
ENV ARM_TENANT_ID $ARM_TENANT_ID
ENV ARM_SUBSCRIPTION_ID $ARM_SUBSCRIPTION_ID

WORKDIR /terraform-modules
COPY . /terraform-modules

RUN cd test && go test -run TestRgModule
