kubeProxyReplacement: strict
k8sServiceHost: ${kind_cluster_name}-control-plane
k8sServicePort: 6443
socketLB:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false
